### PR TITLE
DO NOT MERGE: Add WIP exemplar storage

### PR DESCRIPTION
**Pull request by cstyan**
Want to put the WIP exemplar storage into one of our environments so people can play around with it.

Note: at the moment this is just my branch for the upstream PR plus the latest commit to add relabelling.

### CODE REVIEW

**Comment by rfratto** [comment]
I'm a little confused on what the next steps for this feature are. The PR here is to merge into the `master` branch, but AFAIK nothing is using that (not grafana/agent, anyway). Could you help me understand what the goals are here?

**Comment by rfratto** [comment]
Ah, sorry, didn't read the PR descrpition :upside_down_face: If the point is for people to play around with it, does it really need to go into master?

**Comment by cstyan** [comment]
@rfratto no I meant to open the PR against our 2.17.1 branch but the github UI was being janky.

**Comment by rfratto** [comment]
We haven't discussed this as part of our downstream repo strategy, but dealing with conflicts caused by other feature branches seems tricky. If you rebase, then the upstream PR will include all our other features.

I think the "right" way to do this is manually merging at the command line and fixing conflicts at merge time? It's a pain but that's the only thing I can think of.

**Comment by cstyan** [comment]
@rfratto pretty easy to fix, I just needed to rebase to our 2.17.1 branch instead of upstream 2.17.1  I didn't expect there to be merge conflicts so I didn't choose that as the base branch initially.

I don't have plans to put this into the agent in the near future, just deploy to a single instance in one environment for now.

**Comment by gotjosh** [comment]
If that's the case then @cstyan, I don't see a reason to include it in the release-x branch. You should be able to just run it directly from your branch right?

**Comment by cstyan** [comment]
@gotjosh I guess so. Could just go back to basing off 2.17.1 and run that.

Without really thinking I just thought this had to be merged into something :D

**Comment by bboreham** [comment]
Should this be closed, as exemplars were merged upstream?

**Pull request closed without merging**
